### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by justgoinggoxixi** [luo-yining/CFDBench#1]
Please ask big brother, the code used in the environment version can be marked, I python3.12 and torch2.1 when running many versions conflict

**Comment by chen-yingfa** [comment]
Hello, sorry for the late response, but are there any specific error messages? We ran this code on multiple computers with multiple PyTorch and Python versions, and all of them seem to run fine.

**Comment by justgoinggoxixi** [comment]
> Hello, sorry for the late response, but are there any specific error messages? We ran this code on multiple computers with multiple PyTorch and Python versions, and all of them seem to run fine.

I have solved the problem caused by the tap package. The typed-argument-parser package should be installed in python3

**Comment by justgoinggoxixi** [comment]
![微信截图_20231128104122](https://github.com/luo-yining/CFDBench/assets/133960814/db59d72f-5025-49af-8be3-8a54902aa906)
In dam's packet, only subfolders such as case001 are entered, and there are no subsets of bc, geo, and prop after opening, but a series of folders at the beginning of case, and the code cannot be executed against dam, the error is as follows:
python train_auto.py --model fno --data_name dam_case
in get_dam_auto_datasets
assert case_dirs
AssertionError

**Comment by chen-yingfa** [comment]
I have added a requirements.txt file containing information on essential packages with commit 88ec058.

Thank you for notifying about this error on the Dam dataset, I will check out this dataset tonight when I get back to my dorms. 

It seems that this is an error separate from the original error raised in this issue, I have submitted a new issue for handling this dataset error, please navigate to #2 for further discussion. Therefore, I am closing this issue. For
