### ISSUE TITLE
`CfdNN` not found

### ISSUE THREAD

**Issue by ANTAGNIST** [luo-yining/CFDBench#4]
Dear Yining Luo and Yingfa Chen:
    Thanks for your excellent codes shared with us, but I had some questions about it. That is below:
中文版：
在CFDBench-main/src/models/pinn.py文件中
`
from .base_model import CfdNN
`
但是没有CfdNN这个函数或模块
English Version:
In the CFDBench-main/src/models/pinn.py modules
`
from .base_model import CfdNN
`
I didn't find out the module named CfdNN
![image](https://github.com/luo-yining/CFDBench/assets/62687411/a4ab02df-c3f8-47d5-9629-4e267a8ac120)
![image](https://github.com/luo-yining/CFDBench/assets/62687411/83585879-62d7-4f1b-aa13-4bd1170a694a)

**Comment by chen-yingfa** [comment]
`pinn.py` 这个代码是没有用到的，在最新的版本已经去掉了，请重新 pull 一下。
