### ISSUE TITLE
src.dataset.__init__.py 没有"cavity"文件的运行

### ISSUE THREAD

**Issue by ANTAGNIST** [luo-yining/CFDBench#5]
在24行
`
assert problem_name in ["cylinder", "tube", "dam", "cylinder"]
`
以及34行
`
    elif problem_name == "cylinder":
        # data_dir = Path("data", data_name)
        train_data, dev_data, test_data = get_cavity_datasets(
            data_dir / problem_name,
            case_name=subset_name,
            norm_props=norm_props,
            norm_bc=norm_bc,
        )
        return train_data, dev_data, test_data
`
还有94行
`
    elif problem_name == "cylinder":
        train_data, dev_data, test_data = get_cavity_auto_datasets(
            data_dir / problem_name,
            case_name=subset_name,
            norm_props=norm_props,
            norm_bc=norm_bc,
            delta_time=delta_time,
        )
        return train_data, dev_data, test_data
`
这里的problem_name与下方的get_cavity_auto_datasets不符，也许需要改成"cavity"

**Comment by luo-yining** [comment]
请问问题已经解决了吗？

**Comment by ANTAGNIST** [comment]
已经解决了，感谢大神热心回复并修改代码

在 2024年3月6日星期三，luo-yining ***@***.***> 写道：
