### ISSUE TITLE
训练完模型后修改args.py中mode: str = "test"，无法运行模型文件

### ISSUE THREAD

**Issue by ANTAGNIST** [luo-yining/CFDBench#6]
![image](https://github.com/luo-yining/CFDBench/assets/62687411/5421fda8-671c-47f9-b3d8-8ee05e4015e1)
大佬您好：
  我训练时候的src/args.py中的mode: str = "train-test"，能训练并预测模型，这不会出错。但当我将src/args.py中的mode: str = "test"，我于src.utils.py中的`get_best_ckpt()`中`ckpt_dirs = sorted(output_dir.glob("ckpt-*"))`断点发现，`ckpt_dirs`返回空字符串，我搞不清楚为什么会这样，希望大佬能解惑。
非常感谢！

另外，我做了一张该代码的uml图，如有不正确的地方，希望各位指正~
https://drive.google.com/file/d/1jc0of_o-XIJvoqIjQMnoM6aUn5m3bm6j/view?usp=sharing
![cfdBench drawio](https://github.com/luo-yining/CFDBench/assets/62687411/415b1395-a073-4324-af72-a667a08329b2)

**Comment by ANTAGNIST** [comment]
找到原因了，是output_dir: str = "../result"，而不是"result"

**Comment by luo-yining** [comment]
如果还有其他问题，请重开issue

**Comment by chen-yingfa** [comment]
Send me an email if you have urgent issues, chenyingfa1999 (at) qq (dot) com

**Comment by ANTAGNIST** [comment]
okay, I will do it, thank you for your reply!

在 2024年3月6日星期三，Chen Yingfa ***@***.***> 写道：
