### ISSUE TITLE
Questions about how to run the code

### ISSUE THREAD

**Issue by yezhuhengli** [luo-yining/CFDBench#7]
![3](https://github.com/luo-yining/CFDBench/assets/161319030/cf6274d5-af67-428a-8724-0d5e7501c317)
![2](https://github.com/luo-yining/CFDBench/assets/161319030/cf5ccb23-c7fb-4a21-9e6a-848f49fa2e20)
![1](https://github.com/luo-yining/CFDBench/assets/161319030/d10cdf4f-8cb5-43c5-ad13-b7616dc5a936)

**Comment by chen-yingfa** [comment]
What is the version of your Python?

For image 1, you are not supposed to directly call `import dataset` in a Python REPL environment.

For image 2, you are executing the terminal command in the wrong directory.

**Comment by yezhuhengli** [comment]
我的python版本3.7.16  
好的 那我在试一试

**Comment by yezhuhengli** [comment]
那这行代码 python train.py --model deeponet --data dam_prop_geo该在哪个页面执行
我直接运行train.py也会产生有关类的报错就像这个TypeError: 'type' object is not subscriptable 该怎么解决

**Comment by chen-yingfa** [comment]
请问可以提供具体报错信息吗？

`python train.py ...` 应该在 src 目录下执行的

另外，你的 Python 版本应该运行不了的，建议跟我们 README 中的保持一致。

**Comment by yezhuhengli** [comment]
好的 那我更新一下python版本再试试

**Comment by yezhuhengli** [comment]
![1](https://github.com/luo-yining/CFDBench/assets/161319030/4abb9cbd-3f58-4a0c-96fb-c888718e1eea)
你好我现在运行到这里出现了这个错误 有什么解决办法吗

**Comment by chen-yingfa** [comment]
可以给看看完整的报错信息吗（图中终端输出的后面和前面）？直接拷贝即可，截图可能太大了。

**Comment by yezhuhengli** [comment]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\yes\n\Baseline\CFDbench\CFDBench-main\src\train.py", line 350, in <module>
    main()
  File "C:\Users\Administrator\Desktop\yes\n\Baseline\CFDbench\CFDBench-main\src\train.py", line 306, in main
    train_data, dev_data, test_data = get_dataset(
                                      ^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\yes\n\Baseline\CFDbench\CFDBench-main\src\dataset\__init__.py", line 36, in get_dataset
    train_data, dev_data, test_data = get_cavity_datasets(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\yes\n\Baseline\CFDbench\CFDBench-main\src\dataset\cavity.py", line 375, in get_cavity_datasets
    assert len(case_dirs) > 0
AssertionError

**Comment by chen-yingfa** [comment]
看起来是没有找到数据，你有按照README的方式下载并存放到正确位置了吗？

**Comment by chen-yingfa** [comment]
如果方便，你可以给我（通过邮件）发你的微信联系方式，看看能不能快点解决问题

**Comment by yezhuhengli** [comment]
![2](https://github.com/luo-yining/CFDBench/assets/161319030/0f831f3a-c437-4641-aaf6-519d287652fb)
![3](https://github.com/luo-yining/CFDBench/assets/161319030/89ba75fe-ee23-4f86-85f4-c9d9fb95af71)
我是这样存放数据的不知道有没有问题

**Comment by yezhuhengli** [comment]
哦哦 好的这是我的微信号Kukunii 麻烦你了

**Comment by chen-yingfa** [comment]
数据需要按照[README的这里](https://github.com/luo-yining/CFDBench?tab=readme-ov-file#prepare-data) 所说的存放

**Comment by chen-yingfa** [comment]
我已经私信你，就关掉这个issue了
